using SimlifiezYaml.Core.Enums;
using SimlifiezYaml.Core.Models;
using SimlifiezYaml.Core.Services;
using Xunit;

namespace SimlifiezYaml.Core.Tests;

/// <summary>
/// Tests for the refactored architecture improvements in Phase 3.
/// Tests YAML assembler, trigger configuration, and service refactoring.
/// </summary>
public class Phase3ArchitectureTests
{
    #region PipelineYamlAssembler Tests

    [Fact]
    public void YamlAssembler_BuildsCompleteYaml()
    {
        var assembler = new PipelineYamlAssembler()
            .AddHeader("test-pipeline")
            .AddTrigger("main", "develop")
            .AddVariables("variables:\n  buildConfig: Release")
            .StartStages();

        var yaml = assembler.Build();
        Assert.Contains("# Generated by SimlifiezYaml", yaml);
        Assert.Contains("# Pipeline: test-pipeline", yaml);
        Assert.Contains("trigger:", yaml);
        Assert.Contains("- main", yaml);
        Assert.Contains("- develop", yaml);
        Assert.Contains("variables:", yaml);
        Assert.Contains("stages:", yaml);
    }

    [Fact]
    public void YamlAssembler_FluentInterfaceWorks()
    {
        var assembler = new PipelineYamlAssembler();
        // Verify method chaining works
        var result = assembler
            .AddHeader("test")
            .AddTrigger("main")
            .AddVariables(null)
            .StartStages();
        
        Assert.NotNull(result);
        var yaml = result.Build();
        Assert.NotEmpty(yaml);
    }

    [Fact]
    public void YamlAssembler_HandlesNullVariables()
    {
        var assembler = new PipelineYamlAssembler()
            .AddHeader("test")
            .AddVariables(null)
            .AddVariables("")
            .AddVariables("   ");

        var yaml = assembler.Build();
        // Should not duplicate blank lines
        Assert.DoesNotContain("\n\n\n", yaml);
    }

    [Fact]
    public void YamlAssembler_HandlesNoStages()
    {
        var assembler = new PipelineYamlAssembler()
            .AddHeader("test")
            .AddTrigger("main")
            .StartStages();

        var yaml = assembler.Build();
        Assert.Contains("stages:", yaml);
        Assert.EndsWith("stages:", yaml.TrimEnd());
    }

    [Fact]
    public void YamlAssembler_DefaultTriggerBranches()
    {
        var assembler = new PipelineYamlAssembler()
            .AddHeader("test")
            .AddTrigger();  // No args = default

        var yaml = assembler.Build();
        Assert.Contains("- main", yaml);
        Assert.Contains("- develop", yaml);
    }

    [Fact]
    public void YamlAssembler_CustomTriggerBranches()
    {
        var assembler = new PipelineYamlAssembler()
            .AddHeader("test")
            .AddTrigger("release/*", "hotfix/*");

        var yaml = assembler.Build();
        Assert.Contains("- release/*", yaml);
        Assert.Contains("- hotfix/*", yaml);
        Assert.DoesNotContain("- main", yaml);
    }

    [Fact]
    public void YamlAssembler_AddsCustomStage()
    {
        var stageYaml = "- stage: CustomStage\n  displayName: 'Custom'";
        var assembler = new PipelineYamlAssembler()
            .AddHeader("test")
            .StartStages()
            .AddStage(stageYaml);

        var yaml = assembler.Build();
        Assert.Contains("CustomStage", yaml);
        Assert.Contains("Custom", yaml);
    }

    [Fact]
    public void YamlAssembler_IgnoresEmptyStages()
    {
        var assembler = new PipelineYamlAssembler()
            .AddHeader("test")
            .StartStages()
            .AddStage(null)
            .AddStage("")
            .AddStage("   ");

        var yaml = assembler.Build();
        // Should only have header and stages line
        Assert.Contains("stages:", yaml);
    }

    #endregion

    #region TriggerConfig Tests

    [Fact]
    public void TriggerConfig_Default()
    {
        var config = TriggerConfig.Default;
        Assert.Contains("main", config.IncludeBranches);
        Assert.Contains("develop", config.IncludeBranches);
        Assert.False(config.TriggerAll);
        Assert.Empty(config.ExcludeBranches);
    }

    [Fact]
    public void TriggerConfig_MainOnly()
    {
        var config = TriggerConfig.MainOnly;
        Assert.Single(config.IncludeBranches);
        Assert.Contains("main", config.IncludeBranches);
    }

    [Fact]
    public void TriggerConfig_AllBranches()
    {
        var config = TriggerConfig.AllBranches;
        Assert.True(config.TriggerAll);
    }

    [Fact]
    public void TriggerConfig_CustomBranches()
    {
        var config = new TriggerConfig
        {
            IncludeBranches = new[] { "prod/*", "release/*" },
            ExcludeBranches = new[] { "release/beta" }
        };
        Assert.Equal(2, config.IncludeBranches.Count);
        Assert.Single(config.ExcludeBranches);
    }

    [Fact]
    public void TriggerConfig_PathFilters()
    {
        var config = new TriggerConfig
        {
            PathFilters = new[] { "src/**", "!src/tests/**" }
        };
        Assert.Equal(2, config.PathFilters.Count);
    }

    #endregion

    #region PipelineDefinition Integration Tests

    [Fact]
    public void PipelineDefinition_HasTriggerConfig()
    {
        var definition = new PipelineDefinition
        {
            Name = "test",
            Trigger = TriggerConfig.MainOnly
        };
        Assert.NotNull(definition.Trigger);
        Assert.Contains("main", definition.Trigger.IncludeBranches);
    }

    [Fact]
    public void PipelineDefinition_DefaultTrigger()
    {
        var definition = new PipelineDefinition { Name = "test" };
        Assert.NotNull(definition.Trigger);
        Assert.Contains("main", definition.Trigger.IncludeBranches);
        Assert.Contains("develop", definition.Trigger.IncludeBranches);
    }

    #endregion

    #region Architecture Refactoring Tests

    [Fact]
    public void Refactoring_ReducesServiceComplexity()
    {
        // This test verifies that the refactored service is simpler
        // by checking that PipelineYamlAssembler handles YAML composition
        var assembler = new PipelineYamlAssembler();
        Assert.NotNull(assembler);
        
        // Verify single responsibility: assembler only builds YAML
        var yaml = assembler
            .AddHeader("test")
            .AddTrigger("main")
            .StartStages()
            .Build();
        
        Assert.IsType<string>(yaml);
        Assert.NotEmpty(yaml);
    }

    [Fact]
    public void Refactoring_EliminatesHardcodedBranches()
    {
        // Before: branches were hardcoded as "main", "develop"
        // After: configurable via TriggerConfig
        var config1 = new TriggerConfig { IncludeBranches = new[] { "main" } };
        var config2 = new TriggerConfig { IncludeBranches = new[] { "release/*" } };
        
        Assert.Single(config1.IncludeBranches);
        Assert.Single(config2.IncludeBranches);
        Assert.NotEqual(config1.IncludeBranches[0], config2.IncludeBranches[0]);
    }

    #endregion
}
