using System.Text;
using System.Text.RegularExpressions;
using SimlifiezYaml.Core.Abstractions;
using SimlifiezYaml.Core.Models;
using SimlifiezYaml.Core.Yaml;

namespace SimlifiezYaml.Core.Services;

/// <summary>
/// Assembles Azure DevOps pipeline YAML from individual sections.
/// Separates YAML composition concerns from pipeline orchestration logic.
/// Follows Single Responsibility Principle.
/// </summary>
public sealed class PipelineYamlAssembler
{
    private readonly StringBuilder _yaml = new();

    /// <summary>
    /// Adds the YAML header comment and metadata.
    /// </summary>
    public PipelineYamlAssembler AddHeader(string pipelineName)
    {
        _yaml.AppendLine("# Generated by SimlifiezYaml - Enterprise Azure DevOps Pipeline");
        _yaml.AppendLine($"# Pipeline: {pipelineName}");
        return this;
    }

    /// <summary>
    /// Adds the trigger section with configurable branches.
    /// </summary>
    public PipelineYamlAssembler AddTrigger(params string[]? branches)
    {
        if (branches == null || branches.Length == 0)
            branches = new[] { "main", "develop" };

        _yaml.AppendLine("trigger:");
        _yaml.AppendLine("  branches:");
        _yaml.AppendLine("    include:");
        foreach (var branch in branches)
        {
            _yaml.AppendLine($"      - {branch}");
        }
        _yaml.AppendLine();
        return this;
    }

    /// <summary>
    /// Adds the variables section if variables are provided.
    /// </summary>
    public PipelineYamlAssembler AddVariables(string? variables)
    {
        if (!string.IsNullOrWhiteSpace(variables))
        {
            _yaml.AppendLine(variables);
            _yaml.AppendLine();
        }
        return this;
    }

    /// <summary>
    /// Marks the beginning of the stages section.
    /// </summary>
    public PipelineYamlAssembler StartStages()
    {
        _yaml.AppendLine("stages:");
        return this;
    }

    /// <summary>
    /// Adds a Key Vault pre-job stage if configured.
    /// </summary>
    public PipelineYamlAssembler AddKeyVaultStage(KeyVaultConfig? keyVault, IKeyVaultYamlService keyVaultService)
    {
        if (keyVault == null || string.IsNullOrWhiteSpace(keyVault.KeyVaultName))
            return this;

        _yaml.AppendLine("- stage: KeyVaultPreJob");
        _yaml.AppendLine("  displayName: 'Load Key Vault secrets'");
        _yaml.AppendLine("  jobs:");
        _yaml.AppendLine("  - job: KeyVault");
        _yaml.AppendLine("    steps:");
        _yaml.AppendLine(YamlBuilder.Indent(keyVaultService.GeneratePreJobSteps(keyVault), 6));
        return this;
    }

    /// <summary>
    /// Adds any stage with custom content.
    /// </summary>
    public PipelineYamlAssembler AddStage(string? stageYaml)
    {
        if (!string.IsNullOrWhiteSpace(stageYaml))
        {
            _yaml.AppendLine(stageYaml);
        }
        return this;
    }

    /// <summary>
    /// Adds the Infrastructure as Code stage if configured.
    /// </summary>
    public PipelineYamlAssembler AddIacStage(
        InfrastructureAsCodeConfig? iaC,
        IIacYamlService iacService,
        IReadOnlyList<string> environments)
    {
        if (iaC == null)
            return this;

        var env = environments.FirstOrDefault() ?? "test";
        var steps = string.Join(Environment.NewLine, iacService.GenerateIacSteps(iaC, env));
        _yaml.AppendLine($$"""
- stage: Infrastructure
  displayName: 'Infrastructure as Code'
  dependsOn: Artifact
  condition: succeeded()
  jobs:
  - job: IaC
    steps:
{{YamlBuilder.Indent(steps, 6)}}
""");
        return this;
    }

    /// <summary>
    /// Adds the Rollback stage if configured.
    /// </summary>
    public PipelineYamlAssembler AddRollbackStage(
        RollbackConfig rollback,
        IRollbackYamlService rollbackService,
        IReadOnlyList<string> environments)
    {
        if (!rollback.Enabled)
            return this;

        var lastEnv = environments.LastOrDefault() ?? "prod";
        _yaml.AppendLine($$"""
- stage: Rollback
  displayName: 'Rollback on failure'
  dependsOn: Deploy_{{YamlBuilder.ToIdentifier(lastEnv)}}
  condition: failed()
  jobs:
  - job: RollbackJob
    steps:
{{YamlBuilder.Indent(string.Join(Environment.NewLine, rollbackService.GenerateRollbackSteps(rollback)), 6)}}
""");
        return this;
    }

    /// <summary>
    /// Adds notification stages. Success notifications run only when the last deployment
    /// succeeded; failure notifications run when any earlier stage failed. The outcome has to be
    /// decided at stage level: a step-level <c>failed()</c> would only look at the notify job itself.
    /// </summary>
    public PipelineYamlAssembler AddNotificationStages(
        IReadOnlyList<NotificationConfig> notifications,
        NotificationStepGenerator notificationGenerator,
        PipelineDefinition definition)
    {
        if (notifications.Count == 0)
            return this;

        var lastEnv = definition.Environments.LastOrDefault() ?? "prod";
        var successSteps = notificationGenerator.GenerateSteps(definition, succeeded: true);
        if (successSteps.Count > 0)
        {
            AppendNotifyStage("Notify_Success", "Notify on success",
                $"Deploy_{YamlBuilder.ToIdentifier(lastEnv)}", "succeeded()", successSteps);
        }

        var failureSteps = notificationGenerator.GenerateSteps(definition, succeeded: false);
        if (failureSteps.Count > 0)
        {
            // Depend directly on every stage so failed() is true whichever one failed.
            var allStages = StageNames().Where(n => !n.StartsWith("Notify_", StringComparison.Ordinal)).ToList();
            var dependsOn = allStages.Count == 0 ? "[]" : "\n" + string.Join("\n", allStages.Select(n => $"  - {n}"));
            AppendNotifyStage("Notify_Failure", "Notify on failure", dependsOn, "failed()", failureSteps);
        }

        return this;
    }

    private void AppendNotifyStage(string name, string displayName, string dependsOn, string condition, IReadOnlyList<string> steps)
    {
        _yaml.AppendLine($$"""
- stage: {{name}}
  displayName: {{YamlBuilder.YamlString(displayName)}}
  dependsOn: {{dependsOn}}
  condition: {{condition}}
  jobs:
  - job: Notify
    steps:
{{YamlBuilder.Indent(string.Join("\n", steps), 6)}}
""");
    }

    /// <summary>Names of the stages added so far, in order.</summary>
    private IEnumerable<string> StageNames() =>
        StageNameRegex.Matches(_yaml.ToString()).Select(m => m.Groups[1].Value);

    private static readonly Regex StageNameRegex = new(@"^- stage: ([A-Za-z0-9_]+)\s*$", RegexOptions.Multiline);

    /// <summary>
    /// Gets the assembled YAML document.
    /// </summary>
    public string Build() => _yaml.ToString().TrimEnd();
}
