using System.Text;
using System.Text.RegularExpressions;
using SimlifiezYaml.Core.Abstractions;
using SimlifiezYaml.Core.Generators;
using SimlifiezYaml.Core.Models;
using SimlifiezYaml.Core.Yaml;

namespace SimlifiezYaml.Core.Services;

/// <summary>
/// Assembles Azure DevOps pipeline YAML from individual sections.
/// Separates YAML composition concerns from pipeline orchestration logic.
/// Follows Single Responsibility Principle.
/// </summary>
public sealed class PipelineYamlAssembler
{
    private readonly StringBuilder _yaml = new();

    /// <summary>
    /// Adds the YAML header comment and metadata.
    /// </summary>
    public PipelineYamlAssembler AddHeader(string pipelineName)
    {
        _yaml.AppendLine("# Generated by SimlifiezYaml - Enterprise Azure DevOps Pipeline");
        _yaml.AppendLine($"# Pipeline: {pipelineName}");
        return this;
    }

    /// <summary>
    /// Adds the trigger section with configurable branches.
    /// </summary>
    public PipelineYamlAssembler AddTrigger(params string[]? branches)
    {
        if (branches == null || branches.Length == 0)
            branches = new[] { "main", "develop" };

        _yaml.AppendLine("trigger:");
        _yaml.AppendLine("  branches:");
        _yaml.AppendLine("    include:");
        foreach (var branch in branches)
        {
            _yaml.AppendLine($"      - {branch}");
        }
        _yaml.AppendLine();
        return this;
    }

    /// <summary>
    /// Adds the trigger section from a <see cref="TriggerConfig"/>, including branch excludes and path filters.
    /// </summary>
    public PipelineYamlAssembler AddTrigger(TriggerConfig trigger)
    {
        var include = trigger.TriggerAll || trigger.IncludeBranches.Count == 0
            ? new[] { "'*'" }
            : trigger.IncludeBranches.Select(YamlBuilder.YamlString).ToArray();

        _yaml.AppendLine("trigger:");
        _yaml.AppendLine("  branches:");
        _yaml.AppendLine("    include:");
        foreach (var branch in include)
            _yaml.AppendLine($"      - {branch}");
        if (trigger.ExcludeBranches.Count > 0)
        {
            _yaml.AppendLine("    exclude:");
            foreach (var branch in trigger.ExcludeBranches)
                _yaml.AppendLine($"      - {YamlBuilder.YamlString(branch)}");
        }

        var includePaths = trigger.PathFilters.Where(p => !p.StartsWith('!')).ToList();
        var excludePaths = trigger.PathFilters.Where(p => p.StartsWith('!')).Select(p => p[1..]).ToList();
        if (includePaths.Count > 0 || excludePaths.Count > 0)
        {
            _yaml.AppendLine("  paths:");
            if (includePaths.Count > 0)
            {
                _yaml.AppendLine("    include:");
                foreach (var path in includePaths)
                    _yaml.AppendLine($"      - {YamlBuilder.YamlString(path)}");
            }
            if (excludePaths.Count > 0)
            {
                _yaml.AppendLine("    exclude:");
                foreach (var path in excludePaths)
                    _yaml.AppendLine($"      - {YamlBuilder.YamlString(path)}");
            }
        }
        _yaml.AppendLine();
        return this;
    }

    /// <summary>
    /// Adds the variables section if variables are provided.
    /// </summary>
    public PipelineYamlAssembler AddVariables(string? variables)
    {
        if (!string.IsNullOrWhiteSpace(variables))
        {
            _yaml.AppendLine(variables);
            _yaml.AppendLine();
        }
        return this;
    }

    /// <summary>
    /// Sets the default agent pool for every job that does not choose its own.
    /// </summary>
    public PipelineYamlAssembler AddPool(string poolConfiguration)
    {
        _yaml.AppendLine("pool:");
        _yaml.AppendLine($"  {poolConfiguration}");
        _yaml.AppendLine();
        return this;
    }

    /// <summary>
    /// Marks the beginning of the stages section.
    /// </summary>
    public PipelineYamlAssembler StartStages()
    {
        _yaml.AppendLine("stages:");
        return this;
    }

    /// <summary>
    /// Adds any stage with custom content.
    /// </summary>
    public PipelineYamlAssembler AddStage(string? stageYaml)
    {
        if (!string.IsNullOrWhiteSpace(stageYaml))
        {
            _yaml.AppendLine(stageYaml);
        }
        return this;
    }

    /// <summary>
    /// Adds notification stages. Success notifications run only when the last deployment
    /// succeeded; failure notifications run when any earlier stage failed. The outcome has to be
    /// decided at stage level: a step-level <c>failed()</c> would only look at the notify job itself.
    /// </summary>
    public PipelineYamlAssembler AddNotificationStages(
        IReadOnlyList<NotificationConfig> notifications,
        NotificationStepGenerator notificationGenerator,
        PipelineDefinition definition)
    {
        if (notifications.Count == 0)
            return this;

        var lastEnv = definition.Environments.LastOrDefault() ?? "prod";
        var successSteps = notificationGenerator.GenerateSteps(definition, succeeded: true);
        if (successSteps.Count > 0)
        {
            AppendNotifyStage("Notify_Success", "Notify on success",
                $"Deploy_{YamlBuilder.ToIdentifier(lastEnv)}", "succeeded()", successSteps);
        }

        var failureSteps = notificationGenerator.GenerateSteps(definition, succeeded: false);
        if (failureSteps.Count > 0)
        {
            // Depend directly on every stage so failed() is true whichever one failed.
            var allStages = StageNames().Where(n => !n.StartsWith("Notify_", StringComparison.Ordinal)).ToList();
            var dependsOn = allStages.Count == 0 ? "[]" : "\n" + string.Join("\n", allStages.Select(n => $"  - {n}"));
            AppendNotifyStage("Notify_Failure", "Notify on failure", dependsOn, "failed()", failureSteps);
        }

        return this;
    }

    private void AppendNotifyStage(string name, string displayName, string dependsOn, string condition, IReadOnlyList<string> steps)
    {
        _yaml.AppendLine($$"""
- stage: {{name}}
  displayName: {{YamlBuilder.YamlString(displayName)}}
  dependsOn: {{dependsOn}}
  condition: {{condition}}
  jobs:
  - job: Notify
    steps:
{{YamlBuilder.Indent(string.Join("\n", steps), 6)}}
""");
    }

    /// <summary>Names of the stages added so far, in order.</summary>
    private IEnumerable<string> StageNames() =>
        StageNameRegex.Matches(_yaml.ToString()).Select(m => m.Groups[1].Value);

    private static readonly Regex StageNameRegex = new(@"^- stage: ([A-Za-z0-9_]+)\s*$", RegexOptions.Multiline);

    /// <summary>
    /// Gets the assembled YAML document.
    /// </summary>
    public string Build() => _yaml.ToString().TrimEnd();
}
