using System.Text;
using SimlifiezYaml.Core.Abstractions;
using SimlifiezYaml.Core.Generators;
using SimlifiezYaml.Core.Models;

namespace SimlifiezYaml.Core.Services;

public sealed class PipelineGeneratorService : IPipelineGeneratorService
{
    private readonly IVariableGroupService _variableGroupService;
    private readonly IKeyVaultYamlService _keyVaultService;
    private readonly BuildStageGenerator _buildGenerator;
    private readonly TestStageGenerator _testGenerator;
    private readonly ArtifactStageGenerator _artifactGenerator;
    private readonly DeploymentStageGenerator _deploymentGenerator;
    private readonly NotificationStepGenerator _notificationGenerator;
    private readonly GovernanceValidator _governanceValidator;
    private readonly IYamlExplanationService _explanationService;
    private readonly IAgentDiagnosticsService _agentDiagnosticsService;
    private readonly IIacYamlService _iacService;
    private readonly IRollbackYamlService _rollbackService;

    public PipelineGeneratorService(
        IVariableGroupService variableGroupService,
        IKeyVaultYamlService keyVaultService,
        BuildStageGenerator buildGenerator,
        TestStageGenerator testGenerator,
        ArtifactStageGenerator artifactGenerator,
        DeploymentStageGenerator deploymentGenerator,
        NotificationStepGenerator notificationGenerator,
        GovernanceValidator governanceValidator,
        IYamlExplanationService explanationService,
        IAgentDiagnosticsService agentDiagnosticsService,
        IIacYamlService iacService,
        IRollbackYamlService rollbackService)
    {
        _variableGroupService = variableGroupService;
        _keyVaultService = keyVaultService;
        _buildGenerator = buildGenerator;
        _testGenerator = testGenerator;
        _artifactGenerator = artifactGenerator;
        _deploymentGenerator = deploymentGenerator;
        _notificationGenerator = notificationGenerator;
        _governanceValidator = governanceValidator;
        _explanationService = explanationService;
        _agentDiagnosticsService = agentDiagnosticsService;
        _iacService = iacService;
        _rollbackService = rollbackService;
    }

    public GeneratedPipeline Generate(PipelineDefinition definition)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# Generated by SimlifiezYaml - Enterprise Azure DevOps Pipeline");
        sb.AppendLine($"# Pipeline: {definition.Name}");
        sb.AppendLine("trigger:");
        sb.AppendLine("  branches:");
        sb.AppendLine("    include:");
        sb.AppendLine("      - main");
        sb.AppendLine("      - develop");
        sb.AppendLine();

        var variables = _variableGroupService.GeneratePipelineVariables(definition);
        if (!string.IsNullOrWhiteSpace(variables))
        {
            sb.AppendLine(variables);
            sb.AppendLine();
        }

        sb.AppendLine("stages:");

        if (definition.KeyVault != null && !string.IsNullOrWhiteSpace(definition.KeyVault.KeyVaultName))
        {
            sb.AppendLine("- stage: KeyVaultPreJob");
            sb.AppendLine("  displayName: 'Load Key Vault secrets'");
            sb.AppendLine("  jobs:");
            sb.AppendLine("  - job: KeyVault");
            sb.AppendLine("    steps:");
            sb.AppendLine(Yaml.YamlBuilder.Indent(_keyVaultService.GeneratePreJobSteps(definition.KeyVault), 6));
        }

        var stages = new StringBuilder();
        stages.AppendLine(_buildGenerator.Generate(definition));
        stages.AppendLine(_testGenerator.Generate(definition));
        stages.AppendLine(_artifactGenerator.Generate(definition));

        if (definition.IaC != null)
            AppendIacStage(stages, definition);

        stages.AppendLine(_deploymentGenerator.Generate(definition));
        AppendRollbackStage(stages, definition, _rollbackService);
        AppendNotificationStage(stages, definition);

        sb.AppendLine(stages.ToString().TrimEnd());

        var yaml = sb.ToString();
        var validation = _governanceValidator.ValidateAll(definition, yaml);
        validation = validation.Concat(_keyVaultService.Validate(definition.KeyVault)).ToList();

        string? diagnosticScript = null;
        if (definition.AgentDiagnostics != null)
            diagnosticScript = _agentDiagnosticsService.GenerateDiagnosticScript(definition.AgentDiagnostics);

        return new GeneratedPipeline
        {
            Yaml = yaml,
            Explanations = _explanationService.ExplainYaml(yaml),
            ValidationResults = validation,
            DiagnosticScript = diagnosticScript
        };
    }

    private void AppendIacStage(StringBuilder stages, PipelineDefinition definition)
    {
        var env = definition.Environments.FirstOrDefault() ?? "test";
        var steps = string.Join(Environment.NewLine, _iacService.GenerateIacSteps(definition.IaC!, env));
        stages.AppendLine($"""
- stage: Infrastructure
  displayName: 'Infrastructure as Code'
  dependsOn: Artifact
  condition: succeeded()
  jobs:
  - job: IaC
    steps:
{Yaml.YamlBuilder.Indent(steps, 6)}
""");
    }

    private static void AppendRollbackStage(StringBuilder stages, PipelineDefinition definition, IRollbackYamlService rollbackService)
    {
        if (!definition.Rollback.Enabled) return;
        var lastEnv = definition.Environments.LastOrDefault() ?? "prod";
        stages.AppendLine($"""
- stage: Rollback
  displayName: 'Rollback on failure'
  dependsOn: Deploy_{lastEnv}
  condition: failed()
  jobs:
  - job: RollbackJob
    steps:
{Yaml.YamlBuilder.Indent(string.Join(Environment.NewLine, rollbackService.GenerateRollbackSteps(definition.Rollback)), 6)}
""");
    }

    private void AppendNotificationStage(StringBuilder stages, PipelineDefinition definition)
    {
        if (definition.Notifications.Count == 0) return;
        var lastEnv = definition.Environments.LastOrDefault() ?? "prod";
        var steps = string.Join(Environment.NewLine, _notificationGenerator.GenerateSteps(definition));
        stages.AppendLine($"""
- stage: Notify
  displayName: 'Pipeline notifications'
  dependsOn: Deploy_{lastEnv}
  condition: always()
  jobs:
  - job: Notify
    steps:
{Yaml.YamlBuilder.Indent(steps, 6)}
""");
    }
}
